### ISSUE TITLE
Funcionamiento

### ISSUE THREAD

**Issue by xrtechnology** [indexa-git/l10n-dominicana#1014]
Saludos, Excelente trabajo con este modulo de Comprobante fiscales. 

Por favor necesito ayuda en el usa de la funcionalidad ya que no se como generar el archivo 607,606 y las facturas de compra informales, y menores. 

Si tienen algun video se lo agradeceria infinito.

**Comment by jlopezg** [comment]
Hola @xrtechnology 

Por el momento los reportes de la DGII no están disponibles (únicamente en versión 12).

Sobre los Comprobantes de Compra y Gasto Menor, puede revisar la [documentación](https://github.com/indexa-git/l10n-dominicana/tree/15.0/l10n_do_accounting#facturas-de-compras). En ella se explica cómo registrar las facturas de compra.
