### ISSUE TITLE
No puedes modificar el campo "Es Fiscal?" si ya existen facturas validades en este diario!

### ISSUE THREAD

**Issue by jm1global** [indexa-git/l10n-dominicana#1015]
Cómo puedo instalar la función de l10-dominicana en una db con de producción que ya, ha tenido facturas creadas.

Cuando intento guardar el diario con la opción de "Es Fiscal", me aparece este mensaje: 
No puedes modificar el campo "Es Fiscal?" si ya existen facturas validades en este diario!

Sls, y gracias por el gran aporte que realizan.

**Comment by jm1global** [comment]
Me olvidaba mencionar que estoy trabajando con la versión 15.

**Comment by jlopezg** [comment]
Hola @jm1global 

En primer lugar disculpe la demora en responder.

Por seguridad y básicamente para que no haya, de manera mal intencionada (o por desconocimiento), una manipulación del estatus fiscal de un diario, Odoo **no** permite convertir un diario **no fiscal** a fiscal (y viceversa) una vez se hayan generado documentos con dicho diario.

**Documentación relevante:**
[Diarios](https://github.com/indexa-git/l10n-dominicana/tree/15.0/l10n_do_accounting)
[Facturas de venta](https://github.com/indexa-git/l10n-dominicana/tree/15.0/l10n_do_accounting#facturas-de-ventas)

Me parece que con esto les pueden surgir alguno de los siguientes casos de uso:

**1- Necesitan que este diario sea fiscal y que sus facturas también lo sean.**:
Para esto tendrían que, primero, poner en estado borrador todas las facturas actuales de dicho diario. Una vez hecho esto podrán configurar el diario como fiscal.
Nota: hacer esto implica que las facturas deben volver a validarse, y por lo tanto deben tomar un NCF. Para más información sobre cómo validar facturas fiscales consulte la documentación sobre diarios y facturas.

**2- Quieren mantener el estatus no fiscal de las facturas actuales y utilizar otro diario para las fiscales**:
Para este caso solo necesitan crear un nuevo diario de ventas y configurarlo como fiscal.

**3- Quieren mantener el estatus no fiscal de las facturas actuales y a su vez, con el mismo diario, emitir facturas fiscales**:
Esto no es posible. Forzar al sistema para que haga esto solo desencadenaría una cantidad indeterminada de inconsistencias que es preferible evitar.
