### ISSUE TITLE
Odoo v 16 the button to install is not visible  "installable": False, in __manifest__.py

### ISSUE THREAD

**Issue by jpshort** [indexa-git/l10n-dominicana#1018]
Type: General

**Describe the bug**
Odoo Version: 16
[A clear and concise description of the bug]

The button to install is not available

**Steps to Reproduce**
1. Go to '...' Applications

**Expected behavior**
[A clear and concise description of your expectation]

**Additional context and screenshots**
[Add any other information such as screenshots, videos, messages]
![image](https://user-images.githubusercontent.com/12738468/210005180-b8970aec-1b94-4b57-bd72-85be68c981e8.png)

**Sample Code / Stack Trace**
```
XXX
```

**Configuration information**
Operating System:
Python version:

**Comment by jpshort** [comment]
Revisar el __manifest__,py

"installable": False,
    "auto_install": False,
    "application": False,

**Comment by akevinieron** [comment]
Hi Pedro!

The module is set to "installable: False" because it is not yet intended for use in a production environment.

In a dev environment can be installed changing this parameter in the manifest.
