### ISSUE TITLE
Cómo configurar secuencia automática de los comprobantes NCF

### ISSUE THREAD

**Issue by hyemst** [indexa-git/l10n-dominicana#1034]
Saludos, Equipo

Necesito ayuda o orientación de parte ustedes. 

Cómo puedo configurar la secuencia automática de los comprobantes NCF en odoo 15?
Tengo que ponerlo manual porque no encuentro la funcionalidad o como hacerlo.

Cordial saludos, 

Rafael del Rosario

**Comment by jlopezg** [comment]
Hola @hyemst 

En la [documentación](https://github.com/indexa-git/l10n-dominicana/tree/15.0/l10n_do_accounting#diarios) del módulo se explica esto.
