### ISSUE TITLE
[15.0][BUG] Allows the same number of documents, in invoices with the same supplier.

### ISSUE THREAD

**Issue by Rikylora30** [indexa-git/l10n-dominicana#1039]
Type: General

**Describe the bug**
Odoo Version: 15.0

It should not allow validating supplier fiscal invoices, with the same receipt number and the same supplier.

**Steps to Reproduce**
1. Create a supplier fiscal invoice with your document number and validate it.
2. Create another supplier fiscal invoice with the same supplier of the previous invoice, with the same document number and validate

Thanks in advance.

**Comment by jlopezg** [comment]
Hola @Rikylora30 

Gracias por reportar el issue. Lo estaremos revisando en cuanto podamos.

Recuerda que también puede proponer un PR para resolver el caso.
