### ISSUE TITLE
[15.0][BUG] Permissions error when canceling fiscal invoices

### ISSUE THREAD

**Issue by Rikylora30** [indexa-git/l10n-dominicana#1040]
Type: General

**Describe the bug**
Odoo Version: 15.0

When going to a fiscal invoice, with a user with the "Can Cancel Fiscal Invoices" permission, clicking the button, cancel entry, gives a permissions error.

**Steps to Reproduce**
1. Go to the user settings and activate the permission, "Can cancel Fiscal invoices".
2. Disable "Administration/Settings" permission.
3. Go to a validated fiscal invoice.
4. Click on the "Cancel Entry" button"
5. You see the permissions error.

**Additional context and screenshots**
![Screenshot from 2023-03-16 10-28-31](https://user-images.githubusercontent.com/47247430/225652984-ffa11ebb-0c30-4ac8-b2fa-29e7a8e70697.png)

Should be able to allow users to cancel invoices without "Admin / Settings" permissions.

Thanks in advance.

**Comment by jlopezg** [comment]
Hola @Rikylora30 

Gracias por reportar el issue. Lo estaremos revisando en cuanto podamos.

Recuerda que también puede proponer un PR para resolver el caso.

**Comment by Rikylora30** [comment]
Gracias @jlopezg  Lo tendré presente.

**Comment by jlopezg** [comment]
Resuelto en #1094
