### ISSUE TITLE
Error registrar facturas diario proveedores-no permite guardar

### ISSUE THREAD

**Issue by hyemst** [indexa-git/l10n-dominicana#1107]
Saludos, 

Cuenta 51010100 Costos de Bienes

"No puedes usar esta cuenta (11080101 ITBIS Pagado en Compras de Bienes Locales) en este diario, consulta la sección 'Control-Acceso' en la pestaña 'Configuración avanzada' en el diario relacionado."

Recibimos este error cuando agregamos una factura de compra de bienes y ponemos el itbis. No nos permite guardar la factura poniéndole el ITBIS. Si lo quitamos si permite guardarlo. 

Porque sale este error y cuál es la solución?

Atte. 
Rafael

**Comment by jlopezg** [comment]
Hola @hyemst 

El error que menciona no está relacionado con ninguno de los módulos de este repositorio, por lo que no podemos darte una solución.

En todo caso, el mismo mensaje de error le está indicando lo que debe hacer.
