### ISSUE TITLE
Cash in/out pos odoo16

### ISSUE THREAD

**Issue by rreyes2** [indexa-git/l10n-dominicana#1114]
La funcion de sacar y entrar/entrar dinero no funciona. odoo pos ver 16

**Comment by jlopezg** [comment]
Hola @rreyes2 

Este repositorio, en su rama 16.0, no contiene ningún módulo que dependa del Punto de Ventas.

Te invito a revisar la [documentación](https://www.odoo.com/documentation/16.0/applications/sales/point_of_sale.html) oficial de Odoo para entender cómo funciona.

Un saludo.
