### ISSUE TITLE
Problemas al instalar en Odoo 16 comunity

### ISSUE THREAD

**Issue by Manuelvaldezs** [indexa-git/l10n-dominicana#1116]
Saludos tengo días intentando instalar la localización Dominicana en Odoo 16 comunity no sale para instalar el addon lo tengo el directorio incluso cambié la raíz del directorio y nada no me funciona fuera bueno que hubiera una guía o Algo para instalarlo porque en internet en estos casos la documentación no es muy buena gracias

**Comment by jlopezg** [comment]
Hola @Manuelvaldezs 

Una correcta configuración de los addons path permite instalar los módulos de este repositorio sin ningún problema. Te recomiendo que luego de documentarte sobre el caso, te asegures de que estás ejecutando a Odoo pasándole como parámetro el archivo de configuración correcto y que este último contenga también los path del repositorio.

Un saludo.
