### ISSUE TITLE
Detalle de Cuentas Impactadas en Documentos

### ISSUE THREAD

**Issue by ljacobo** [indexa-git/l10n-dominicana#1150]
**Describe the feature you are requesting**
[Sería posible agregar a la pestaña de OTRA INFORMACION / INFORMACION ADICIONAL en los documentos de ventas, compras, recepción de inventario, etc, las cuentas contables que impactan dicho documento?]

**Reasons for requesting this feature**
[Una manera de que la persona de finanzas pueda tener una visión de las cuentan que afectan cada tipo de documento.]

**Describe alternatives you've considered**
[A clear and concise description of any alternative solutions or features you've considered]

**Additional context**
[ADJUNTO IMAGEN CON EJEMPLO DE FACTURA DE VENTAS en ODOO v12 CE
![Screenshot 2024-03-20 at 11 52 48 AM](https://github.com/indexa-git/l10n-dominicana/assets/38470609/b9af5e6a-f5f2-465e-b1d1-35a8ba1afcb1)
]

**Comment by jlopezg** [comment]
Hola @ljacobo 

De este "Feature request" se desprenden varias informaciones:

1. Si lo que estás solicitando es para versión 12, te informo que solo estamos dando mantenimiento a las últimas 3 versiones publicadas en este repositorio. Para versiones aún más antiguas solo hacemos bugfixing.
2. En este repositorio solo trabajamos las funcionalidades mínimas requeridas para emitir facturas fiscales dominicanas. Para cualquier funcionalidad adicional invitamos a que hereden los módulos (l10n_do_accounting) en un módulo de ustedes e implementen la funcionalidad que requieren. Ver [documentación](https://github.com/indexa-git/l10n-dominicana/blob/16.0/README.md) del repositorio.
3. Me parece que eso que requieres ya Odoo lo hace de manera nativa. Hay un permiso que se llama **Show Full Accounting Features** o **Mostrar características de contabilidad completas** en español, que hace específicamente eso. Echale un ojo.
