### ISSUE TITLE
Odoo 14 Consultas

### ISSUE THREAD

**Issue by ljacobo** [indexa-git/l10n-dominicana#1151]
**Describe your question**
1- Cómo podemos llevar un control de los NCF utilizados? Ya que en esta versión, no nos permite ajustar las secuencias de comprobantes fiscales.

2- DGII Reports. Existe una opción de paga para lograr exportar las declaraciones de la DGII para esta versión.

**What have you tried?**
Actualmente uso la version 12 CE y estoy probando en una bd nueva la version 14 CE.

Gracias!

**Comment by jlopezg** [comment]
Hola @ljacobo 

Q: **Cómo podemos llevar un control de los NCF utilizados? Ya que en esta versión, no nos permite ajustar las secuencias de comprobantes fiscales.**
A: Deben desarrollar, heredando el módulo `l10n_do_accounting`, la funcionalidad ya que no está presente en el módulo y por cuestiones que se explican en la [documentación](https://github.com/indexa-git/l10n-dominicana/blob/16.0/README.md) no se estará incluyendo.

Q: **DGII Reports. Existe una opción de paga para lograr exportar las declaraciones de la DGII para esta versión.**
A: Al menos en Indexa no, pero puede que hayan otras empresas o particulares que sí lo hagan.

**Comment by ljacobo** [comment]
Gracias @jlopezg!
