### ISSUE TITLE
Deshabilitar Validación DGII

### ISSUE THREAD

**Issue by luisjacoboattuendum** [indexa-git/l10n-dominicana#1185]
**Describe your question**
Es posible deshabilitar la validación el RNC con la DGII al momento de crear un contacto o validar una factura?

Para la versión Odoo v11 CE. Este caso en particular es que dicha instancia estará en un ambiente totalmente sin conexión.

**What have you tried?**
He probado editando los valores del parámetro dgii.wsmovil, de TRUE a FALSE.

Gracias.

**Comment by andrp92** [comment]
@luisjacoboattuendum Hola, gracias por tu consulta.

Desactivar ese parámetro debería ser suficiente deshabilitar la búsqueda de contacto. Con respecto a la validación en la factura, esa parte no la veo configurable en el código de v11. Por lo que si hacen un PR podemos con gusto incluirlo.

Saludos cordiales,

**Comment by luisjacoboattuendum** [comment]
En el caso de crear los contactos, aún estando FALSE el parámetro, trata de validarlo con la DGII.

Sobre el PR, no sabría por donde comenzar. Sería examinar el código.

Gracias.
