### ISSUE TITLE
ncf_pos: Fecha vencimiento de la secuencia

### ISSUE THREAD

**Issue by jrodmaster** [indexa-git/l10n-dominicana#207]
https://github.com/odoo-dominicana/l10n-dominicana/blob/a790f1b1bcf60cbe3316e30610a601e5a07fc25e/ncf_pos/static/src/xml/ncf_ticket.xml#L49

Extraer la fecha de vencimiento de la BD y que no sea en un texto plano

**Comment by gustavovalverde** [comment]
Sí, fue un force mío...mientras tanto 😄

@eneldoserrata y @frankpenalo, les dejo ese task. Ya en el backend se hala a la factura, faltaría en el POS.

**Comment by gustavovalverde** [comment]
**Nota** Durante este año completo, todas las secuencias van a vencer el 31/12/2019. Por eso no lo prioricé mucho.

**Comment by akevinieron** [comment]
@gustavovalverde @eneldoserrata Esto no es necesario en el ticket del POS. Podemos cerrar esto, que opinan??

**Comment by gustavovalverde** [comment]
@akevinieron, sí esto es necesario.

**Comment by akevinieron** [comment]
@gustavovalverde Al momento de escribir ese comentario habia leido en un documento de la dgii que esto no aplicaba para este tipo de facturas, aunque honestamente ese documento es un poco confuso porque habla de soluciones fiscales y no deja muy claro si fuera de soluciones fiscales tampoco era necesario.

Pero, aqui revisando decenas de facturas de comida y demas de los ultimos meses, de lugares diferentes, con comprobante fiscal y consumidor final, ninguna tiene fecha de vencimiento de secuencia. Esto no comprueba que no sea necesario, solo lo comento como un punto de referencia para investigar esto mejor.

**Comment by jldm3000** [comment]
Saludos, recuerden cambiar la fecha en el ncf_ticket.xml mientras realizan la corrección definitiva.
Ya conversado en el grupo de Telegram @gustavovalverde

**Comment by gustavovalverde** [comment]
@jldm3000 habrá que ver quién de la comunidad se motiva a hacer el cambio, ya que en mi caso no desarrollo para el Punto de Venta.

**Comment by juhenriquez** [comment]
@gustavovalverde Creo esto se puede cerrar.

**Comment by jlopezg** [comment]
@akevinieron podemos cerrar este issue?

**Comment by dg18** [comment]
Revisar #734 con una solución provisional, ya que el ncf_ticket.xml se encuentra desactualizado ya.
Saludos,

**Comment by jlopezg** [comment]
Cerrado por falta de seguimiento.
