### ISSUE TITLE
Nota de Crédito -  El saldo aplicado a otras facturas en 0.

### ISSUE THREAD

**Issue by jeffryjdelarosa** [indexa-git/l10n-dominicana#593]
#### Impacted versions
10.0, 11.0 , 12.0

#### Steps to reproduce
Las Notas de Creditos cuando el saldo a favor es aplicado a otra factura el valor debe aparercer en la Columun 27 o mas bien  **Otro de Forma de Pago.**

#### Current behavior
https://github.com/odoo-dominicana/l10n-dominicana/blob/ea15b2e6853c1ab8926ed3068bfb7c546204929b/dgii_reports/models/dgii_report.py#L563-L590
El cual es resultado lo coloca en CERO, ya que tipo no es una pago por medio del Diario, sino más es una Nota de Credito.'

#### Expected behavior
Cuando a una factura le es aplicada un pago o este se mixto por concepto de factura de credito pueda salir en otra forma de pago en el 607.

Para mas explicacion de referente a este tema lo podemos encontrar en esta link
[Ver Más Detalle Ejemplo en DGII](https://ayuda.dgii.gov.do/dgii/topics/nota-de-credito-607-factura-pagada?utm_source=notification&utm_medium=email&utm_campaign=new_reply&utm_content=reply_button&reply[id]=20457128#reply_20457128)

**Comment by jeffryjdelarosa** [comment]
@jlopezg @raulovallet @gustavovalverde Aqui lo que le mencionaba. en el URL tengo el ejemplo. No tengo mucho.

**Comment by jlopezg** [comment]
@jeffryjdelarosa por favor describir la sección **Steps to reproduce** de manera que indique paso por paso cómo lograr el escenario para reproducir el issue.

**Comment by jlopezg** [comment]
Cerrado por falta de seguimiento

**Comment by jeffryjdelarosa** [comment]
@jlopezg hay hermano perdón .

Lo que sucede es que cuando una factura es pagada está busca en el método en que fue pagado.

pero cuando una factura es pagada con una NC en el 607 debe estar en Otra Forma de Pago, esto mayormente sucede cuando ese saldo queda pendiente y se le aplica a otra factura. Me explico

Viene el cliente paga por transferencia o con TC hoy sucedes que días luego  solicita una NC. Pero como la factura ya está pagada cuando se hace la NC se queda un salgo a favor y ese saldo a favor de aplica a otra factura diferente a la que se modificó.

ahora bien si tiene otra forma cómo proceder déjeme saber
