### ISSUE TITLE
Make a documentation for the basics funcionalities

### ISSUE THREAD

**Issue by akevinieron** [indexa-git/l10n-dominicana#656]
**This is a real good first issue to begging help the local community.**

We need to show:

- how to install the modules
- how to configure the company
- how to configure the fiscal types sequences
- and how to work with it

**You can do it!**

**Comment by akevinieron** [comment]
There is a 'docs' directory but the info inside is totally outdated. You can delete all these files and make new ones

**Comment by jlopezg** [comment]
Resuelto en #978
