### ISSUE TITLE
Corregir referencia de módulos en el README.md

### ISSUE THREAD

**Issue by evaldez89** [indexa-git/l10n-dominicana#664]
Type: General

**Describe the bug**
Odoo Version: 13
El README.md de la versión 13 aun hace referencia a los nombres anteriores de los módulos, que no son compatibles con la esta versión.

**Steps to Reproduce**
1. Go to [README.md](https://github.com/odoo-dominicana/l10n-dominicana/blob/13.0/README.md)
1. See error
![image](https://user-images.githubusercontent.com/12959163/93116822-cd17d680-f68b-11ea-891b-6ec6100e3b07.png)

**Expected behavior**
Nombrar los módulos correctamente y hacer referencia a los enlaces actuales

**Additional context and screenshots**
![image](https://user-images.githubusercontent.com/12959163/93117061-3bf52f80-f68c-11ea-80e5-8a5ac82ef472.png)

**Comment by andrp92** [comment]
Gracias @evaldez89 por el feedback. Disculpa que no se le dio calor a este punto en su debido momento. Han habido muchos cambios desde entonces, incluyendo el readme que fue actualizado recientemente. Por lo que este issue ya no aplica.

Cualquier sugerencia de mejora será bienvenida 👍
