### ISSUE TITLE
Campo "afecta a" en notas de débito

### ISSUE THREAD

**Issue by jromero-octagono** [indexa-git/l10n-dominicana#794]
Odoo V12

1. Ir a contabilidad
2. Hacer una nota de débito a una factura de suplidor
3. El campo afecta a no está visible en el formulario de la factura y tampoco en el pdf

**Comportamiento esperado**
Campo visible en ambos casos

Agregando "or o.is_nd" sería solucionado en el pdf ya que el tipo de una nota de débito sigue siendo in_invoice

<span t-if="(o.type == 'out_refund' or o.type == 'in_refund' ** or o.is_nd**) and (o.origin_out != False)">
        <strong>NCF modificado:</strong>
        <span t-field="o.origin_out"/>
        <br/>
</span>

**Comment by jlopezg** [comment]
@jromero-octagono esto está listo.

Aprovecho para informarles que Octagono puede convertirse en sponsor de este proyecto haciendo un micro aporte mensual. Visite [este](https://github.com/sponsors/indexa-git) link para más información.
