### ISSUE TITLE
Error raises when cash in/out in bank statements

### ISSUE THREAD

**Issue by akevinieron** [indexa-git/l10n-dominicana#812]
In the core, Odoo has cash in/out method in bank statements.

This line cause an error while executing this methods:
https://github.com/indexa-git/l10n-dominicana/blob/d36eececfe44a70e834828a634e4310122935305/ncf_pos/models/cash_box.py#L31

![image](https://user-images.githubusercontent.com/2160489/121753636-c619d980-cae0-11eb-818d-c90891ac2ab8.png)

**Comment by jlopezg** [comment]
Issue cerrado porque la versión 12 ya no está recibiendo mantenimiento.
