### ISSUE TITLE
POS Order get the NCF but the invoice isn't

### ISSUE THREAD

**Issue by akevinieron** [indexa-git/l10n-dominicana#813]
A POS Order needs to know if NCF should be sent to the invoice verifying the "ncf_control" configuration of invoice journal. But instead, this fields is related to the sale journal. This is a mistake because force to make sale journal a fiscal journal for no reason, because this journal never work with invoices, only with pos orders no invoiced.

https://github.com/indexa-git/l10n-dominicana/blob/d36eececfe44a70e834828a634e4310122935305/ncf_pos/models/pos_order.py#L67

This problem can be solve by changing this related field to the invoice journal instead sale journal.

**Comment by jlopezg** [comment]
Issue cerrado porque la versión 12 ya no está recibiendo mantenimiento.
