### ISSUE TITLE
POS Orders havent NCF field in the form view

### ISSUE THREAD

**Issue by akevinieron** [indexa-git/l10n-dominicana#814]
In tree view is NCF field but in the form view this field doesn't appear only the NCF Invoice (related field).

https://github.com/indexa-git/l10n-dominicana/blob/d36eececfe44a70e834828a634e4310122935305/ncf_pos/views/pos_view.xml#L13

**Comment by jlopezg** [comment]
Issue cerrado porque la versión 12 ya no está recibiendo mantenimiento.
