### ISSUE TITLE
Improvement to order info in pos order form

### ISSUE THREAD

**Issue by akevinieron** [indexa-git/l10n-dominicana#815]
The POS Order extra info tab in the form view is missing an important information: Invoice Journal.

![image](https://user-images.githubusercontent.com/2160489/121756057-e51b6a00-cae6-11eb-818f-32ce5426f7cf.png)

**Comment by jlopezg** [comment]
Issue cerrado porque la versión 12 ya no está recibiendo mantenimiento.
