### ISSUE TITLE
On POS Payment, the authorization number in credit card payment isn't mandatory

### ISSUE THREAD

**Issue by akevinieron** [indexa-git/l10n-dominicana#816]
In the POS, we can have multiple payment methods. When the payment method is bank type, a popup raises asking the authorization transaction number. This popup isn't mandatory, can be by passed only clicking "Accept" without writing any information.

This number is 6 digits long and generally appears above the total in POS (VeriFone) vouchers. By asking for this number we avoid the possible mistake the cashier can make by accidentally clicking this payment method.

![image](https://user-images.githubusercontent.com/2160489/121756759-3cbad500-cae9-11eb-831c-ba0c34447d89.png)

**Comment by jlopezg** [comment]
Issue cerrado porque la versión 12 ya no está recibiendo mantenimiento.
