### ISSUE TITLE
Wrong field name in account move cancel wizard

### ISSUE THREAD

**Issue by jromero-octagono** [indexa-git/l10n-dominicana#821]
Type: General

**Describe the bug**
Odoo Version: 14.0
[A clear and concise description of the bug]

Error trying to cancel an invoice, in line 35 wizard/account_move_cancel.py
The field "invoice_payment_state" needs to be replaced with "payment_state"
as this is the correct field name in account_move

**Comment by jlopezg** [comment]
Hola @jromero-octagono 

La versión 14 no está lista y por el momento no se le está invirtiendo tiempo.

Les invito a convertirse en [Sponsors](https://github.com/sponsors/indexa-git) de este proyecto para que podamos continuar con el desarrollo de esta versión 14.
