### ISSUE TITLE
Vista de fiscal sequences

### ISSUE THREAD

**Issue by Vitolaviagra** [indexa-git/l10n-dominicana#929]
Acabo de añadir todos los modulos necesarios para la configuracion de la contabilidad Dominicana, pero no puedo visualizar las secuencias fiscales al momento de ajustar a verdadero el booleano (l10n_latam_use_documents)
@jlopezg

**Comment by jlopezg** [comment]
Hola @Vitolaviagra 

¿Cuál versión estás usando?

**Comment by jlopezg** [comment]
Cerrado por falta de seguimiento.
