### ISSUE TITLE
[14.0][BUG] l10n_do_accounting: internal sequence documents getting a new NCF when cancelling

### ISSUE THREAD

**Issue by jose250698** [indexa-git/l10n-dominicana#933]
Type: General

**Describe the bug**
Odoo Version: 14.0

Cuando tienes N cantidad de facturas de cliente, al cancelar una que no sea la última, un nuevo NCF es consumido.

**Steps to reproduce the behavior:**
Teniendo las facturas B0100000001, B0100000002 y B0100000003, al cancelar la B0100000002, esta toma el NCF B0100000004, haciendo un salto en la secuencia, porque al validarla nuevamente queda con este NCF incorrecto.

**Expected behavior**
Mantener el mismo NCF al cancelar la factura.

**Comment by jlopezg** [comment]
Solved in #934
