### ISSUE TITLE
Secuencias Fiscales

### ISSUE THREAD

**Issue by Vitolaviagra** [indexa-git/l10n-dominicana#938]
Hola que tal todos.

Estoy tratando de poder visualizar las secuencias fiscales luego de implementar los modulos necesarios del repositorio actual.

Estoy trabajando con la version 13 @jlopezg

**Comment by jlopezg** [comment]
@Vitolaviagra podría explicar cuál es el problema?

**Comment by Vitolaviagra** [comment]
Ya pude visualizar las secuencias fiscales, muchas gracias 🙏.  Solo tengo un inconveniente con el pos para la version 13, ya que me esta dando unos errores de dependencia con objetos de ncf.

**Comment by jlopezg** [comment]
@Vitolaviagra abre otro Issue por favor y documentalo
