### ISSUE TITLE
Aun falta el manejo de las secuencias para la version 15?

### ISSUE THREAD

**Issue by jm1global** [indexa-git/l10n-dominicana#988]
Instale el modulo; pero no me sale la pestaña para el manejo de las secuencias en el Diarios contables/Facturas de cliente.

![DiarioFiscal](https://user-images.githubusercontent.com/107966985/186492464-94f34b15-7ab9-47e2-bc6c-99e66578b730.png)

**Comment by jlopezg** [comment]
Hola @jm1global 

¿A cuál pestaña se refiere? 
¿En qué versión estaba dicha pestaña?
¿Podría suministrar una captura de pantalla de la pestaña en cuestión?

**Comment by jm1global** [comment]
Muchas gracias por la pronta respuesta, 

Especificamente, no encuentro el menú para administrar las secuencias de NCF, poder colocar la numeración de inicio hasta. Sería como el control de los mismos. En la parte de la imagen (seleccionada), solo podemos editar la fecha de expiración.
![DiarioFiscal_2](https://user-images.githubusercontent.com/107966985/186720361-74c98d50-72cf-4631-a816-cb1b03cf44b3.png)

La versión de Odoo es 15.0+e-20220803 Versión Enterprise

La pestaña solo la vi en otra version, me parece que la 13

**Comment by jlopezg** [comment]
Por favor lea la [documentación](https://github.com/indexa-git/l10n-dominicana/tree/15.0/l10n_do_accounting#diarios) para la configuración de diarios con esta localización.

Nota: en la versión 13 de esta localización solo se coloca la secuencia inicial, no la final. Para tener más funcionalidades en el manejo de secuencias debe utilizar módulos específicos para esos fines.

**Comment by jm1global** [comment]
Muchas gracias!
