### ISSUE TITLE
Como cargar la secuencia o numero de comprobantes Odoo Comminity 15

### ISSUE THREAD

**Issue by mmarmolejos** [indexa-git/l10n-dominicana#991]
ODOO COMMUNITY 15
![image](https://user-images.githubusercontent.com/87543335/186682625-e92f12b3-9734-4d2d-aff6-7a1bb52e92fa.png)

En esta parte ni me carga, ni me deja editar alguna sugerencia????

**Comment by jlopezg** [comment]
Hola @mmarmolejos 

Primero debe darle a Guardar para que se generen los tipos de comprobantes fiscales.

Para más información consulte la [documentación](https://github.com/indexa-git/l10n-dominicana/tree/15.0/l10n_do_accounting#fiscal-accounting-rep-dominicana) del módulo.
