### ISSUE TITLE
Trabajaran para el l10n_do_pos para la versión 15 de Odoo?

### ISSUE THREAD

**Issue by jm1global** [indexa-git/l10n-dominicana#995]
l10n_do_pos para la versión 15 de Odoo

**Comment by jlopezg** [comment]
Hola @jm1global 

Por el momento no tenemos en planes trabajar con el POS, sin embargo, cualquier persona puede tomar como base el **l10n_do_pos** de la versión 13 y migrarlo a 14 y luego a 15 en este mismo repositorio. Nosotros nos encargaríamos de depurarlo para que quede lo mejor posible.
